DROP DATABASE IF EXISTS GLO2005;
CREATE DATABASE IF NOT EXISTS GLO2005;
USE GLO2005;

CREATE TABLE Movie (
 MovieId INT NOT NULL AUTO_INCREMENT,
 Title VARCHAR(255) NOT NULL,
 Genre VARCHAR(255) NOT NULL,
 Synopsis VARCHAR(255) NOT NULL,
 Length INT NOT NULL,
 Year  INT NOT NULL,
 Country VARCHAR(255) NOT NULL,
 MaturityRating VARCHAR(255) NOT NULL,
 PRIMARY KEY (MovieId));
 
 CREATE TABLE Shows (
 ShowsId INT NOT NULL AUTO_INCREMENT,
 Title VARCHAR(255) NOT NULL,
 Genre VARCHAR(255) NOT NULL,
 Synopsis VARCHAR(255) NOT NULL,
 FromYear INT NOT NULL,
 ToYear  INT NOT NULL,
 Country VARCHAR(255) NOT NULL,
 MaturityRating VARCHAR(255) NOT NULL,
 PRIMARY KEY (ShowsId));
 
 CREATE TABLE Episode (
 EpisodeId INT NOT NULL AUTO_INCREMENT,
 Title VARCHAR(255) NOT NULL,
 Synopsis VARCHAR(255) NOT NULL,
 EpisodeNo INT NOT NULL,
 SeasonNo  INT NOT NULL,
 Length INT NOT NULL,
 FirstAirDate DATE,
 PRIMARY KEY (EpisodeId));
 
 CREATE TABLE User (
 UserId INT NOT NULL AUTO_INCREMENT,
 FirstName VARCHAR(255) NOT NULL,
 LastName VARCHAR(255) NOT NULL,
 UserName VARCHAR(255) NOT NULL,
 Password VARCHAR(255) NOT NULL,
 PRIMARY KEY (UserId));
 
 CREATE TABLE FavoriteMovie (
 FavoriteMovieId INT NOT NULL AUTO_INCREMENT,
 UserID INT NOT NULL NOT NULL,
 MovieID INT NOT NULL,
 PRIMARY KEY (FavoriteMovieId),
 FOREIGN KEY (UserID) REFERENCES User(UserId),
 FOREIGN KEY (MovieID) REFERENCES Movie(MovieID));
 
 CREATE TABLE FavoriteShow (
 FavoriteShowId INT NOT NULL AUTO_INCREMENT,
 UserID INT NOT NULL,
 ShowID INT NOT NULL,
 PRIMARY KEY (FavoriteShowId),
 FOREIGN KEY (UserID) REFERENCES User(UserId),
 FOREIGN KEY (ShowID) REFERENCES Shows(ShowID));