version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "5002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./bd_init:/docker-entrypoint-initdb.d/:ro
  app:
    build: ./app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - db