DROP DATABASE IF EXISTS GLO2005;
CREATE DATABASE IF NOT EXISTS GLO2005;
USE GLO2005;

CREATE TABLE Genre(
  GenreId INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (GenreId)
);

CREATE TABLE Movie (
 MovieId INT NOT NULL AUTO_INCREMENT,
 Title VARCHAR(255) NOT NULL,
 Synopsis VARCHAR(255) NOT NULL,
 Length INT NOT NULL,
 Year  INT NOT NULL,
 Country VARCHAR(255) NOT NULL,
 MaturityRating VARCHAR(255) NOT NULL,
 ImageUrl VARCHAR(255),
 GenreId INT NOT NULL,
 PRIMARY KEY (MovieId),
 FOREIGN KEY (GenreId) REFERENCES Genre(GenreId));
 
 CREATE TABLE TvShow (
 ShowId INT NOT NULL AUTO_INCREMENT,
 Title VARCHAR(255) NOT NULL,
 GenreId INT NOT NULL,
 Synopsis VARCHAR(255) NOT NULL,
 FromYear INT NOT NULL,
 ToYear  INT NOT NULL,
 Country VARCHAR(255) NOT NULL,
 MaturityRating VARCHAR(255) NOT NULL,
 ImageUrl VARCHAR(255),
 VideoUrl VARCHAR(255),
 PRIMARY KEY (ShowId));
 
 CREATE TABLE Episode (
 EpisodeId INT NOT NULL AUTO_INCREMENT,
 Title VARCHAR(255) NOT NULL,
 Synopsis VARCHAR(255) NOT NULL,
 EpisodeNo INT NOT NULL,
 SeasonNo  INT NOT NULL,
 Length INT NOT NULL,
 FirstAirDate DATE,
 ShowId INT NOT NULL,
 PRIMARY KEY (EpisodeId),
 FOREIGN KEY (ShowId) REFERENCES TvShow(ShowId),
 FOREIGN KEY (GenreId) REFERENCES Genre(GenreId));

 CREATE TABLE User (
 UserId INT NOT NULL AUTO_INCREMENT,
 FirstName VARCHAR(255) NOT NULL,
 LastName VARCHAR(255) NOT NULL,
 UserName VARCHAR(255) NOT NULL,
 Password VARCHAR(255) NOT NULL,
 PRIMARY KEY (UserId));
 
 CREATE TABLE FavoriteMovie (
 FavoriteMovieId INT NOT NULL AUTO_INCREMENT,
 UserID INT NOT NULL NOT NULL,
 MovieID INT NOT NULL,
 PRIMARY KEY (FavoriteMovieId),
 FOREIGN KEY (UserID) REFERENCES User(UserId),
 FOREIGN KEY (MovieID) REFERENCES Movie(MovieID));
 
 CREATE TABLE FavoriteShow (
 FavoriteShowId INT NOT NULL AUTO_INCREMENT,
 UserID INT NOT NULL,
 ShowID INT NOT NULL,
 PRIMARY KEY (FavoriteShowId),
 FOREIGN KEY (UserID) REFERENCES User(UserId),
 FOREIGN KEY (ShowID) REFERENCES TvShow(ShowId));